config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/search_results' => 'recipes#search_results'
  get '/search_results/:recipe_id' => 'recipes#search_result'

  resources :users, except: [:index] do
    resources :recipes
    get '/grocery_list' => 'grocery_lists#show'
    patch '/grocery_list' => 'grocery_lists#update'
  end

  resources :sessions, only: [:create]

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  belongs_to :grocery_list
  serialize :ingredients, Array
  serialize :instructions, Array

  validates :title,
    presence: true


end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :recipes
  has_many :grocery_lists
  before_create :create_remember_token
  before_save :normalize_fields

  validates :name,
    presence: true,
    length: { maximum: 50 }

  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.hash(User.new_remember_token)
  end

  def normalize_fields
    self.email.downcase!
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/grocery_lists_controller.rb
class GroceryListsController < ApplicationController
  def update
    @user = current_user
    if params['commit'] == 'Add to My Grocery List'
      @recipe = Recipe.find(params['recipe']['recipe_id'])
      @recipe[:grocery_list?] = true
      @recipe.save
    elsif params["commit"] == "Clear My Grocery List"
      @recipes = Recipe.where(grocery_list?: true)
      @recipes.each do |recipe|
        recipe[:grocery_list?] = false
        recipe.save
      end
    end
    redirect_to user_grocery_list_path(current_user)
  end

  def show
    @user = current_user
    @recipes = Recipe.where(grocery_list?: true)
    @grocery_list_array = []
    @recipes.each do |recipe|
      @grocery_list_array.concat(recipe[:ingredients])
    end

  end



end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action(:find_user, except: [:search_results])
  before_action(:new_recipe, only: [:search_result, :new, :create])
  before_action(:find_recipe, only: [:show, :edit, :update, :destroy])

  def search_results
    @search_terms = params[:q].gsub(" ", "+")
    response_hash = HTTParty.get("http://api.bigoven.com/recipes?any_kw=#{@search_terms}&pg=1&rpp=20&api_key=#{MY_API_KEY}")
    @search_results = response_hash["RecipeSearchResult"]["Results"]["RecipeInfo"]
  end

  def search_result
    get_json

  end

  def new
  end

  def create
    @recipe[:title] = params["recipe"]["title"]
    @recipe[:imageURL] = params["recipe"]["imageURL"]
    @recipe[:description] = params["recipe"]["description"]
    @recipe[:cuisine] = params["recipe"]["cuisine"]
    @recipe[:ingredients] = params["recipe"]["ingredients"].split("$")
    @recipe[:instructions] = params["recipe"]["instructions"].split("$")
    @recipe[:yield] = params["recipe"]["yield"]
    @recipe[:time] = params["recipe"]["time"]
    @recipe[:user_id] = params[:user_id]
    @recipe.save
    redirect_to user_recipes_path(@user)
  end

  def index
    @recipes = Recipe.where(user_id: @user.id)
  end

  def show
  end

  def edit
  end

  def update
    @recipe[:title] = params[:recipe][:title]
    @recipe[:imageURL] = params[:recipe][:imageURL]
    @recipe[:description] = params[:recipe][:description]
    @recipe[:cuisine] = params[:recipe][:cuisine]
    @recipe[:ingredients] = params[:recipe][:ingredients].split(', ')
    @recipe[:instructions] = params[:recipe][:instructions].split('. ')
    @recipe[:yield] = params[:recipe][:yield]
    @recipe[:time] = params[:recipe][:time]
    @recipe[:user_id] = params[:user_id]
    @recipe.save
    redirect_to user_recipes_path(@user)
  end

  def destroy
    @recipe.destroy
    redirect_to user_recipes_path
  end

  private

  def get_json
    @recipe_id = params[:recipe_id]
    response = HTTParty.get("http://api.bigoven.com/recipe/#{@recipe_id}?api_key=#{MY_API_KEY}")
    @recipe_imageURL = response["Recipe"]["ImageURL"]
    @recipe_title = response["Recipe"]["Title"]
    @recipe_description = response["Recipe"]["Description"]
    @recipe_cuisine = response["Recipe"]["Cuisine"]
    @recipe_yield = response["Recipe"]["YieldNumber"].to_s + " " + response["Recipe"]["YieldUnit"].to_s
    @recipe_time = response["Recipe"]["TotalMinutes"]
    @recipe_rating = response["Recipe"]["StarRating"].to_f.round(2)
    @recipe_ingredient_array = response["Recipe"]["Ingredients"]["Ingredient"].map do |ingredient_hash|
      "#{ingredient_hash["Quantity"].to_f.round(2) } #{ingredient_hash["Unit"]} #{ingredient_hash["Name"]}"
    end
    @recipe_instructions = response["Recipe"]["Instructions"].split(". ")
  end

  def recipe_params
    params.require(:recipe).permit(:title, :imageURL, :description, :cuisine, )
  end

  def find_user
    @user = current_user
  end

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def new_recipe
    @recipe = Recipe.new
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # Find the user by email:
    user = User.find_by(email: params[:session][:email].downcase)

    # Test if the user was found AND authenticates
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or root_url
    else
      flash[:error] = 'Invalid email/password'
      redirect_to signin_path
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController <  ApplicationController
  before_action :require_signin, except: [:new, :create]
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  before_action :require_current_user, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to @user
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render  :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation
      )
  end

  def require_current_user
    if !current_user?(@user)
      redirect_to root_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Current User methods:

  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    current_user == user
  end

  # Signin Status methods:

  def signed_in?
    !current_user.nil?
  end

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  # Location Management methods:

  def store_location
    if request.get?
      session[:return_to] = request.url
    end
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  # Security Checkpoint method:

  def require_signin
    unless signed_in?
      store_location
      flash[:error] = 'Please sign in.'
      redirect_to signin_url
    end
  end
end

app/views/common/_signout.html.erb
<% if signed_in? %>

  <%= form_for :session, url: signout_path, method: 'delete' do |f| %>
    <span class="welcomeuser">Welcome, <%= link_to current_user.name, current_user %>!</span>
    <span class="signout"><%= f.submit "Sign out", id: 'signout' %></span>
  <% end %>

  <span class="searchbanner"><%= link_to "Search", root_path %></span>
<br>
  <span class="mycookbooklink"><%= link_to "My Cookbook", user_recipes_path(current_user) %></span>
  <br>
  <span class="mygrocerylistlink"><%= link_to "My Grocery List", user_grocery_list_path(current_user) %></span>

<% else %>
  <span class="loggedoutbanner">Sign up or log in to save recipes to your cookbook!</span>
<br>
  <span class="signinsignup"><%= link_to "Sign In", signin_path %> | <%= link_to "Sign up", signup_path %></span>
<br>
  <span class="searchbanner"><%= link_to "Search", root_path %></span>

<% end %>

app/views/grocery_lists/show.html.erb
<div class="grocery_list">
<h1><%= @user.name %>'s Grocery List</h1>

<div class="grocerylist">
<ul>
<% @grocery_list_array.each do |ingredient| %>
    <li><%= ingredient %></li>
<% end %>
</ul>
</div>


<%= form_tag user_grocery_list_path(@user), method: 'patch' do %>
  <%= submit_tag "Clear My Grocery List" %>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Nixie+One' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Shadows+Into+Light+Two|Nothing+You+Could+Do' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Raleway:300' rel='stylesheet' type='text/css'>
  <title>Mycookbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div  class="navigation">
  <p class="miniwelcome">MyCookbook</p>
   <%= render 'common/signout' %>
  </div>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for [@user, @recipe] do |f|%>
  <%= f.label :title, "What would you like to call your recipe?" %>
  <%= f.text_field "title" %>
<br>
  <%= f.label :imageURL, "Paste URL for image here" %>
  <%= f.text_field "imageURL" %>
<br>
  <%= f.label :description, "Description:" %>
  <br>
  <%= f.text_area "description" %>
<br>
  <%= f.label :cuisine %>
  <%= f.text_field "cuisine" %>
<br>
  <%= f.label :ingredients, "List the ingredients here, separated by commas. Don't forget to include amounts and units!" %>
  <br>
  <%= f.text_area "ingredients" %>
<br>
  <%= f.label :instructions, "Here is where you can clearly list out sentences for the instructions for this recipe." %>
  <br>
  <%= f.text_area "instructions" %>
<br>
  <%= f.label :yield, "How many servings does this provide?" %>
  <%= f.text_field "yield" %>
<br>
  <%= f.label :time, "Total minutes to make?" %>
  <%= f.text_field "time" %>
<br>
  <%= f.submit "Save Recipe to MyCookbook" %>
<% end %>

app/views/recipes/edit.html.erb
<div class="recipeform">

<h1>Edit <%= @recipe.title %></h1>

<%= render "form" %>

</div>

app/views/recipes/index.html.erb
<div class="usercookbook">
<h1><%= @user.name %>'s Cookbook</h1>

<% @recipes.each do |recipe| %>
  <li><%= link_to recipe.title, user_recipe_path(@user,recipe) %></li>
<% end %>

</div>

app/views/recipes/new.html.erb
<div class="recipeform">

<h1>Create Your Own Recipe</h1>

<%= render "form" %>

</div>

app/views/recipes/search_result.html.erb
<div class="search_result">
  <p class="backbutton"><%= link_to "Back to Search Results", :back %></p>
  <div id="image">
    <img src="<%= @recipe_imageURL %>">
    <% if signed_in? %>

      <%= form_for [@user, @recipe] do |f|%>
        <%= hidden_field_tag "recipe[recipe_id]", @recipe_id %>
        <%= hidden_field_tag "recipe[title]", @recipe_title %>
        <%= hidden_field_tag "recipe[imageURL]", @recipe_imageURL %>
        <%= hidden_field_tag "recipe[description]", @recipe_description %>
        <%= hidden_field_tag "recipe[cuisine]",  @recipe_cuisine %>
        <%= hidden_field_tag "recipe[ingredients]", (@recipe_ingredient_array.join("$")) %>
        <%= hidden_field_tag "recipe[instructions]", (@recipe_instructions.join("$")) %>
        <%= hidden_field_tag "recipe[yield]", @recipe_yield %>
        <%= hidden_field_tag "recipe[time]", @recipe_time %>
        <%= submit_tag "Save Recipe to MyCookbook", id: "create" %>
      <% end %>

    <% end %>
  </div>

  <div class="everythingbutimg">
    <h1><%= @recipe_title %></h1>
    <p class="description"><%= @recipe_description %></p>


    <div class="details">
      <p>Cuisine: <%= @recipe_cuisine %></p>
      <p>Servings: <%= @recipe_yield %></p>
      <p>Total Time: <%= @recipe_time %> minutes</p>
      <p>Rating: <%= @recipe_rating %>/5</p>
    </div>
    <div class="ingredients">
      <p>Ingredients:</p>
      <ul>
        <% @recipe_ingredient_array.each do |ingredient| %>
          <li> <%= ingredient %></li>
          <% end %>
      </ul>
    </div>
    <div class="instructions">
      <p>Instructions:</p>
      <ol>
      <% @recipe_instructions.each do |instruction_line| %>
        <li><%= instruction_line %></li>
      <% end %>
      </ol>
    </div>

</div>
</div>

app/views/recipes/search_results.html.erb
<div class="search_results">
<h1>Recipe Results for "<%= @search_terms %>"</h1>

<% @search_results.each do |recipe| %>
  <li>
    <% recipe_id = recipe["RecipeID"] %>
    <a href="/search_results/<%= recipe_id %>" id="recipe-link">
    <img src="<%= recipe["ImageURL"] %>">
    <p><%= recipe["Title"] %></p>

    </a>
  </li>
<% end %>
</div>

app/views/recipes/show.html.erb
<div class="search_result">
<p class="backbutton"><%= link_to "Back to Cookbook", user_recipes_path(current_user) %></p>
<div id="image">
  <img src="<%= @recipe.imageURL %>" class="large-image">
  <div class="nav">
  <%= form_for [@user,@recipe], url: user_grocery_list_path(@user) do |f| %>
      <%= f.hidden_field 'add to grocery list', :value =>'yes' %>
      <%= f.hidden_field :recipe_id, :value => @recipe.id %>
      <%= f.submit "Add to My Grocery List" %>
    <% end %>

    <%= link_to "Edit Recipe", edit_user_recipe_path(@user,@recipe) %>

    <%= form_for [@user,@recipe], method: 'delete' do |f| %>
      <%= f.submit "Delete Recipe from MyCookbook", id: "destroy" %>
    <% end %>
  </div>
</div>

<div class="everythingbutimg">
<h1><%= @recipe.title %></h1>
  <p class="description"><%= @recipe.description %></p>

  <div class="details">
  <p>Cuisine: <%= @recipe.cuisine %></p>
  <p>Servings: <%= @recipe.yield %></p>
  <p>Total Time: <%= @recipe.time %> minutes</p>
  </div>
  <div class="ingredients">
  <p>Ingredients:</p>
  <ul>
    <% @recipe.ingredients.each do |ingredient| %>
      <li> <%= ingredient %></li>
    <% end %>
  </ul>
  </div>
  <div class="instructions">
  <p>Instructions:</p>
    <ol>
    <% @recipe.instructions.each do |instruction_line| %>
      <li><%= instruction_line %></li>
    <% end %>
    </ol>

</div>
</div>
</div>

app/views/users/_user_form.html.erb
<% if @user.errors.any? %>
<b>Errors:</b>
<ul>
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
<br>
  <%= f.label :email %>
  <%= f.text_field :email %>
<br>
  <%= f.label :password %>
  <%= f.password_field :password %>
<br>
  <%= f.label :password_confirmation, 'Confirm Password' %>
  <%= f.password_field :password_confirmation %>
<br>
  <%= f.submit "Submit", id: 'submit' %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit <%= @user.name %></h1>
<%= render "user_form" %>

<hr>

<%= form_for @user, method: 'delete' do |f| %>
  <%= f.submit "Delete" %>
<% end %>

<hr>

<%= link_to "Cancel", @user %>

app/views/users/new.html.erb
<div class="signuppage">
<h1>Sign Up</h1>
<%= render "user_form" %>

</div>

app/views/users/show.html.erb
<div class="userpage">
<h1><%= @user.name %></h1>

<p><%= @user.email %></p>

<p><%= link_to "Edit", edit_user_path(@user) %></p>

</div>

app/views/welcome/index.html.erb
<h1 class="visuallyhidden">Basic Recipe Search</h1>
<div class="welcomepage">

<p class="welcome">Welcome to MyCookbook!</p>


<%= form_tag("/search_results", method: "get") do %>
  <%= label_tag(:q, "What are you craving?", :class => "craving") %>
  <br>
  <%= text_field_tag(:q, nil, :class => "search_field") %>
  <br>
  <%= submit_tag("Basic Recipe Search", :class => "search_button") %>
<% end %>

<% if signed_in? %>
  <%= link_to "Nah, I want to add my own", new_user_recipe_path(current_user) %>
<% end %>
</div>